mutation AddShot(
  $gameId: Int!
  $fromTeamId: Int!
  $fromPlayerId: Int!
  $shotTypeId: Int!
  $hit: Boolean!
) {
  addShot(
    data: {
      gameId: $gameId
      fromTeamId: $fromTeamId
      fromPlayerId: $fromPlayerId
      shotTypeId: $shotTypeId
      hit: $hit
    }
  ) {
    gameId
    fromTeamId
    fromPlayerId
    shotTypeId
    hit
  }
}
