fragment teamActionCount on TeamAreaActionCount {
  count
  time
  x
  y
}

fragment gameActionCount on GameActionCount {
  homeTeam {
    ...teamActionCount
  }
  awayTeam {
    ...teamActionCount
  }
}

query GetGameActionCount {
  games(take: 3) {
    id
    shotCountByArea {
      ...gameActionCount
    }
    hitCountByArea {
      ...gameActionCount
    }
    passCountByArea {
      ...gameActionCount
    }
  }
}
