fragment countByPeriod on TeamShotCountByPeriod {
  count
  shots {
    id
    hit
  }
}

query GetShotCountByPeriod {
  games(take: 2) {
    id
    shotCountByPeriod {
      homeTeam {
        ...countByPeriod
      }
      awayTeam {
        ...countByPeriod
      }
    }
  }
}
