# fragment countByPeriod on TeamShotCountByPeriod {
#   count
#   shots {
#     id
#     hit
#   }
# }

# subscription ShotCountByPeriodUpdated {
#   shotCountByPeriodUpdated {
#     id
#     shotCountByPeriod {
#       homeTeam {
#         ...countByPeriod
#       }
#       awayTeam {
#         ...countByPeriod
#       }
#     }
#   }
# }

# subscription GameUpdated {
#   gameUpdated {
#     ...scheduleGame
#   }
# }
