fragment team on Team {
  id
  name
  abbr
}

fragment shot on Shot {
  id
  time
  hit
  player {
    id
    lastName
  }
}

query GetGames {
  games(take: 10) {
    id
    start
    stop
    homeTeamShots {
      ...shot
    }
    awayTeamShots {
      ...shot
    }
    homeTeam {
      ...team
    }
    awayTeam {
      ...team
    }
  }
}
